### ISSUE TITLE
does the demo model train on mobilnet?

### ISSUE THREAD

**Issue by hufangjian** [Gauravv97/CameraBlur#1]
I flow 
 https://colab.research.google.com/github/Gauravv97/Tensorflow-deeplabV3-TrainSaveResume-on-Android/blob/master/Train_and_Resume_.ipynb#scrollTo=gz9JY6KYPIs- 

to train the model ,but  it is on 'xception_65' and your demon obviously is mobilenet
how can i train mobilenet by cropsize 1025x 1025

**Comment by Gauravv97** [comment]
I've already trained a model of that crop size and it's [Here](https://github.com/Gauravv97/CameraBlur/tree/master/InputSize%201025px)

If you want to train your own you can follow DailyStudio's project [here](https://github.com/dailystudio/ml/tree/master/deeplab) just modify the cropsize to your requirement.

The script you were running was a demonstration and I could use a bigger ,heavier model there so I went with 'xception' one. My idea was to give a choice for various models but I dropped it. That had little to do with this projects model. Hope it helps.

**Comment by hufangjian** [comment]
do you have try to use tflite？From this project https://github.com/tantara/JejuNet, the author convert the model to tflite. but the offical have not support 'tf.image.resize_bilinear' ops in tensorflowlite. do you have same adviser?

**Comment by Gauravv97** [comment]
Will try to figure out what author has done, but on first look, it looks like he/she has removed some layers off the model. As stated by him that he had Google  credit for TPU during his/her esteemed training.
If he has trained his model from scratch I'm sorry I can't implement it coz I don't have that much time.

**Comment by Gauravv97** [comment]
The owner of the repo https://github.com/tantara/JejuNet will post a guide for deeplabv3+ to tflite conversion.. stay tuned to it...
