### ISSUE TITLE
What is the principle about SoftBlur around edges?

### ISSUE THREAD

**Issue by candrwow** [Gauravv97/CameraBlur#4]
I read your code,but don't understand the principle about SoftBlur around edges.
What is the specific function of RadialDist?

**Comment by Gauravv97** [comment]
Hi @candrwow , I got busy with my job and couldn't pay much attention to GitHub much during that time... Hope you understand.
Getting back to your query hopefully which you would have already figured out..
If not the basic explanation is that it takes a binary 2d Mask of an image where the subject ( marked 1 in this 2d array )or the background ( marked 0 ) is and then fills out each pixel of the background (0) with its closest distance to the subject (1) . For example a 0 pixel directly next to a 1 will be marked with radial distance 2 and so on til each pixel gets the closest distance to subject pixels. We can dilate and erode( reverse 0 and 1 ) the edges of our subject mask using this distance.
